use std::env;

fn main() {
    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    
    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(cbindgen::Language::C)
        .with_include_guard("SECURE_CLOUD_CORE_H")
        .with_pragma_once(true)
        .with_autogen_warning("/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("secure_cloud_core.h");
}